# Generated by Django 3.1.7 on 2021-03-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='titile',
            new_name='title',
        ),
    ]
